version: '3.8'

services:
  react-app:
    build: .
    ports:
      - "8000:3000"
    command: npm start
    restart: always
    develop:
      watch:
        - action: sync
          path: ./app
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json